

name: Label issues
on: 
  repository_dispatch:
  
jobs:
  label_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Event Information
        run: |
          echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}'"
      - name: Run tests
        id: algo
        run: |
          echo "Aver si esto anda me vuelvo loko"
      - name: PONG - Dispatch response to received PING
        if: github.event.action == 'ping'
        run: |
          curl -X POST https://api.github.com/repos/hernanr99/pruebaGithubActions/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          --data '{"event_type": "pong", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'", "data": "'"${{ steps.algo.outputs }}"'" }}'
