on:
  workflow_call:
    outputs:
      firstword:
        description: "The first output string"
        value: "juan cruz"
      secondword:
        description: "The second output string"
        value: "eso pepe"
  

jobs:
  build:
    name: Run API
    runs-on: ubuntu-latest
    steps:
      - name: Build API
        run: |
          echo "Build API Cos coso coso es esteee"
          sleep 10s
